services:
  - type: web
    name: ecommerce-pro-api
    env: node
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: ecommerce-db
          property: connectionString
    autoDeploy: true
